services:
  api-desafio-cep:
    build:
      target: dev
      context: .
      dockerfile: api-desafio-cep/Dockerfile
    volumes:
      - ${PWD}/api-desafio-cep/src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  vue-desafio-cep:
    build:
      target: dev
      context: .
      dockerfile: vue-app/Dockerfile
    ports:
      - 9001:3000
    volumes:
      - ${PWD}/vue-app:/app
    #for dev only
    working_dir: /app

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

