services:
  api-desafio-cep:
    build:
      target: dev
      context: ./api-desafio-cep
    volumes:
      - ${PWD}/api-desafio-cep/src:/var/www/html/src
      - ${PWD}/api-desafio-cep/vendor:/var/www/html/vendor
      - ${PWD}/api-desafio-cep/index.php:/var/www/html/index.php
      - ${PWD}/api-desafio-cep/composer.json:/var/www/html/composer.json
      - ${PWD}/api-desafio-cep/composer.lock:/var/www/html/composer.lock
    working_dir: /var/www/html
    networks:
      - app-network
    depends_on:
      - db

  vue-desafio-cep:
    build:
      target: dev
      context: ./vue-app
    ports:
      - 9001:3000
    volumes:
      - ${PWD}/vue-app:/app
    working_dir: /app

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-desafio-cep
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
      - ${PWD}/migrations/init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - app-network

  migrate:
    image: mysql:8.0
    volumes:
      - ./migrations:/migrations
    networks:
      - app-network
    depends_on:
      - db
    entrypoint: /bin/sh -c "/migrations/migrate.sh"

networks:
  app-network:
    driver: bridge
