services:
  pdo:
    class: PDO
    arguments:
      $dsn: 'mysql:host=db;dbname=mydatabase'
      $username: 'myuser'
      $password: 'mypassword'

  App\Repository\DistanceRepository:
    class: App\Repository\DistanceRepository
    arguments:
      $pdo: '@pdo'
    public: true

  App\Interfaces\DistanceRepositoryInterface:
    alias: App\Repository\DistanceRepository
    public: true

  App\Service\CoordinateService:
    class: App\Service\CoordinateService
    public: true

  App\Interfaces\CoordinateServiceInterface:
    alias: App\Service\CoordinateService
    public: true

  App\Service\DistanceServiceInterface:
    alias: App\Service\DistanceService
    public: true

  App\Service\DistanceService:
    class: App\Service\DistanceService
    arguments:
      $distanceRepository: '@App\Interfaces\DistanceRepositoryInterface'
      $coordinateService: '@App\Interfaces\CoordinateServiceInterface'
    public: true

  App\Controller\DistanceController:
    arguments:
      $distanceService: '@App\Service\DistanceServiceInterface'
    public: true
